[[instances]]
name = "first"
swarm = "validators"
id_range = "1..=2"

[[instances]]
name = "swarm1"
swarm = "validators"
id_range = "1..=8"

[[instances]]
name = "swarm2"
swarm = "validators"
id_range = "9..=16"

[[swarms]]
name = "validators"
executable = "/home/stan/tari/dan/target/debug/tari_validator_node"
working_dir = "/home/stan/Litterbox/validators"
ports = ["jrpc_port", "webui", "p2p"]
args = [
    "--base-path",
    "./vn{id}",
    "--rpc-address", "127.0.0.1:{ports[jrpc_port]}",
    "--network",
    "localnet",
    "-plocalnet.p2p.seeds.peer_seeds={seed_peer_1_public_key}::{seed_peer_1_address}",
    "-pvalidator_node.p2p.transport.type=tcp",
    "-pvalidator_node.p2p.transport.tcp.listener_address=/ip4/127.0.0.1/tcp/{ports[p2p]}",
    "-pvalidator_node.public_address=/ip4/127.0.0.1/tcp/{ports[p2p]}",
    "-pvalidator_node.p2p.allow_test_addresses=true",
]
env = { }
actions.on_after_first_start = ["register"]
actions.on_after_start = ["connect-seed-peer"]
#actions.on_interval = [{ interval = "1m", actions = ["register"] }]
actions.options = ["register", "connect-seed-peer"]

[[actions]]
name = "register"
[actions.json_rpc]
url = "http://127.0.0.1:{swarm.instance.ports[jrpc_port]}/json_rpc"
method = "register_validator_node"

[[actions]]
name = "connect-seed-peer"
[actions.json_rpc]
url = "http://127.0.0.1:{swarm.instance.ports[jrpc_port]}/json_rpc"
method = "add_peer"
params.public_key = "{seed_peer_1_public_key}"
params.addresses = ["{seed_peer_1_address}"]
params.wait_for_dial = false

[[actions]]
name = "delete-data-dir"
restart_on_action = true
[actions.fs_rm]
path = "/home/stan/Litterbox/validators/vn{swarm.instance.id}/localnet/data/validator/db"
force = true

[variables]
seed_peer_1_public_key = "52bef4d946a13d3cc39f3adc11471b551109e0f3f7a726a941b4a7d3c3896160"
seed_peer_1_address = "/ip4/127.0.0.1/tcp/12345"
